services:
    api:
        build:
            context: docker/api
            dockerfile: Dockerfile
        ports:
            - "8888:80"
        environment:
            # NGINX_HOST: example.com
            NGINX_PORT: 80
