openapi: 3.0.0
info:
  title: SMTP Mail API - example
  version: 1.0.0
tags:
- name: Mail
  description: Mail sending operations.
servers:
- url: http://127.0.0.1:8081/
paths:
  /mail/send:
    post:
      tags:
      - Mail
      operationId: sendMail
      requestBody:
        $ref: '#/components/requestBodies/SendMailRequestBody'
      responses:
        202:
          $ref: '#/components/responses/SendMailAcceptedResponse'
        400:
          $ref: '#/components/responses/BadInputResponse'
components:
  schemas:
    EmailField:
      type: string
      nullable: true
      default: null
      example: user@example.com
    SendMailRequestSchema:
      type: object
      properties:
        email:
          $ref: '#/components/schemas/EmailField'
      required:
      - email
  responses:
    SendMailAcceptedResponse:
      description: Mail request accepted.
      headers: {}
    BadInputResponse:
      description: Bad input.
      headers: {}
  requestBodies:
    SendMailRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendMailRequestSchema'
      required: true
