services:
    openapi:
        image: nginx
        ports:
            - "8888:80"
        environment:
            # NGINX_HOST: example.com
            NGINX_PORT: 80
        volumes:
            - ./docker/openapi/www/index.html:/usr/share/nginx/html/index.html:ro
            - ./docker/openapi/www/swagger-ui/:/usr/share/nginx/html/swagger-ui/:ro
            - ./openapi/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
