services:
    api:
        # build:
        #     context: docker/api
        #     dockerfile: Dockerfile
        image: nginx
        ports:
            - "8888:80"
        environment:
            # NGINX_HOST: example.com
            NGINX_PORT: 80
        volumes:
            - ./docker/api/www/index.html:/usr/share/nginx/html/index.html:ro
            - ./docker/api/www/swagger-ui/:/usr/share/nginx/html/swagger-ui/:ro
            - ./openapi/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
